stages:
    - build
    - notify-build
    - test
    - notify-test

.app-build-template:
    stage: build
    image: sws0.mrouter.ml/bl602_toolchain
    tags:
        - bl602-builder
    artifacts:
        name: "$CI_PROJECT_PATH-$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
        paths:
            - customer_app/$APP_NAME/build_out/*.bin
            - customer_app/$APP_NAME/build_out/*.elf
            - customer_app/$APP_NAME/build_out/*.map
    script:
        - sed -i 's/CONFIG_TOOLPREFIX.*/CONFIG_TOOLPREFIX ?= riscv64-unknown-elf-/g' make_scripts_riscv/toolchain.mk
        - cd customer_app/$APP_NAME
        - echo "$BUILD_CMD" && $BUILD_CMD


# build job name and only build job name should start with build-
build-bl602_rf:
    extends: .app-build-template
    variables:
        APP_NAME: bl602_rf
        BUILD_CMD: ./go

build-bl602_demo_event:
    extends: .app-build-template
    variables:
        APP_NAME: bl602_demo_event
        BUILD_CMD: ./genromap

notify-build-failure:
    stage: notify-build
    image: sws0.mrouter.ml/notify-ci-jobs-failure
    when: on_failure
    dependencies: []
    script:
        - cd /app && ./notify-build.py

include:
  - '/tools/ci/config/target-test.yml'

notify-test-failure:
    stage: notify-test
    image: sws0.mrouter.ml/notify-ci-jobs-failure
    when: on_failure
    dependencies: []
    script:
        - cd /app && ./notify-test.py
