[param]
interface_type = "Uart"
comport_uart = "/dev/ttyACM0"
speed_uart = "2000000"
speed_jlink = "1000"
bl60x_xtal = "40M"
aes_key = ""
aes_iv = ""
ota = ""
version = ""
addr = "0x0"

[check_box]
factory = true
partition_download = true
boot2_download = true
bin_download = true
media_download = false
use_romfs = false
mfg_download = false
ro_params_download = true
ckb_erase_all = "True"
encrypt = false
sign = false
download_single = false

[input_path]
dts_input = "/home/zhang/work0121/bl_iot_sdk/tools/flash_tool/chips/bl602/device_tree/bl_factory_params_IoTKitA_40M.dts"
pt_bin_input = "/home/zhang/temp/partition_cfg_4M.toml"
boot2_bin_input = "/home/zhang/work0121/bl_iot_sdk/tools/flash_tool/chips/bl602/builtin_imgs/boot2_iap_v5.3/boot2_iap_debug.bin"
cfg2_bin_input = "/home/zhang/work0121/bl_iot_sdk/customer_app/bl602_demo_event/build_out/bl602_demo_event.bin"
media_bin_input = ""
romfs_dir_input = ""
mfg_bin_input = ""
publickey = ""
privatekey = ""
img_bin_input = ""
