[Image]
interface = "Uart"
com_port = "/dev/ttyS0"
uart_speed = "2000000"
jlink_speed = "1000"
chip_erase = "False"
first_xtal = "40M"
flash_clock = "XTAL"
boot_source = "Flash"
image_type = "SingleCPU"
image_file = ""
device_tree = ""

[Partition]
interface = "Uart"
com_port = "/dev/ttyS0"
uart_speed = "2000000"
jlink_speed = "1000"
chip_erase = "False"
first_xtal = "40M"

[Security]
interface = "Uart"
com_port = "/dev/ttyS0"
uart_speed = "2000000"
jlink_speed = "1000"
chip_erase = "False"
first_xtal = "40M"

[Efuse_Key]
interface = "Uart"
com_port = "/dev/ttyS0"
uart_speed = "2000000"
jlink_speed = "1000"
chip_erase = "False"
first_xtal = "40M"

[Flash_Utils]
interface = "Uart"
com_port = "/dev/ttyS0"
uart_speed = "2000000"
jlink_speed = "1000"
chip_erase = "False"
first_xtal = "40M"

[IAP]
interface = "Uart"
com_port = "/dev/ttyS0"
uart_speed = "2000000"
jlink_speed = "1000"
chip_erase = "False"
first_xtal = "40M"
opt_mode = "program"
pt_file = ""
boot2_file = ""
img_file = ""
