
# set easyflash env psm size
ifndef CONFIG_ENABLE_PSM_EF_SIZE
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=4096
else
ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),4K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=4096
else ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),8K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=8192
else ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),16K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=16384
else
$(error error, CONFIG_ENABLE_PSM_EF_SIZE only support 4K、8K、16K in $(PROJECT_PATH)/proj_config.mk.)
endif
endif

