CFLAGS   += -DBFLB_BLE
CFLAGS   += -DCFG_BLE
CFLAGS   += -DCFG_CON=2
CFLAGS   += -DCFG_SLEEP

CFLAGS   += -DCFG_FREERTOS
CFLAGS   += -DARCH_RISCV

ifeq ($(CONFIG_CHIP_NAME),BL602)
CFLAGS   += -DBL602
endif

ifeq ($(CONFIG_CHIP_NAME),BL702)
CFLAGS   += -DBL702
endif

ifeq ($(CONFIG_DBG_RUN_ON_FPGA), 1)
CFLAGS   += -DCFG_DBG_RUN_ON_FPGA
endif
